baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Streaming Data Innovation Day'
theme = 'hugo-theme-learn'

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "oracle"